# Generated by Django 5.2.17 on 2026-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcheck',
            name='input_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
