# Generated by Django 5.2.17 on 2026-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcheck',
            name='ain',
            field=models.CharField(blank=True, help_text='MeshKor Cryptographic Identity', max_length=120, null=True),
        ),
    ]
