# Generated by Django 5.2.17 on 2026-10-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_merge_meshkor_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcheck',
            name='ain',
            field=models.CharField(blank=True, help_text='MeshKor Cryptographic Identity', max_length=255, null=True),
        ),
    ]
