"""
Django settings for kormic_backend project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load ANTHROPIC_API_KEY / GITHUB_TOKEN / etc. from .env before any agent code runs.
load_dotenv(BASE_DIR / ".env")

# First key encrypts new TOTP seeds; all configured keys can decrypt. Supply
# independently of DB credentials, DJANGO_SECRET_KEY and GitHub OAuth keys.
TOTP_SECRET_KEYS = tuple(
    key.strip() for key in os.getenv('TOTP_SECRET_KEYS', '').split(',') if key.strip()
)


# Tests must be hermetic: they should never require Redis/Celery services.
# This covers both `python manage.py test` and direct pytest runs.
TESTING = "test" in sys.argv or "pytest" in Path(sys.argv[0]).name.lower()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (fail closed): an unset/misconfigured DJANGO_DEBUG in a
# deploy environment must never silently open a debug server to the
# internet. Local dev sets DJANGO_DEBUG=true explicitly in .env.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

# Keep the generated key strictly development-only. Production must provide
# an explicit strong secret rather than silently falling back to an
# insecure checked-in value.
_DEV_SECRET_KEY = 'django-insecure-0zav109$orgckjm3w+%%8v!lxt&4)qv68d^w*f%@fid@_y!c83'
if DEBUG:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or _DEV_SECRET_KEY
else:
    SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
    if not SECRET_KEY:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set to a long random value when DJANGO_DEBUG=false."
        )

# Defaults to localhost only (fail closed) so a missing env var on a real
# server rejects Host headers instead of accepting anything ("*"). Any
# server reachable off localhost (staging, prod) must set
# DJANGO_ALLOWED_HOSTS explicitly -- see DEPLOYMENT.md.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HTTPS hardening. Keep local development HTTP-friendly; deployments behind
# the trusted proxy are redirected to HTTPS and receive an initial one-hour
# HSTS policy. Raise HSTS to one year after the production HTTPS path has
# been observed stable.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'django_api',
    'institutes_list',
    'verification',
    'universities',
    'institutes',
    'notifications',
    'project_superuser',
    'url_discovery',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kormic_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kormic_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_raw_db_engine = os.environ.get("DB_ENGINE", "").strip().lower()

if not DEBUG:
    if not _raw_db_engine:
        raise ImproperlyConfigured(
            "DB_ENGINE=postgresql must be set explicitly when DJANGO_DEBUG=false."
        )
    if _raw_db_engine not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured(
            "Production requires DB_ENGINE=postgresql; SQLite is local-development only."
        )

DB_ENGINE = _raw_db_engine or "sqlite"

if DB_ENGINE in {"sqlite", "sqlite3"}:
    sqlite_name = os.environ.get("SQLITE_PATH", "").strip()
    SQLITE_DB_PATH = Path(sqlite_name).expanduser() if sqlite_name else BASE_DIR / "db.sqlite3"
    if not SQLITE_DB_PATH.is_absolute():
        SQLITE_DB_PATH = (BASE_DIR / SQLITE_DB_PATH).resolve()

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_DB_PATH,
            "OPTIONS": {
                "timeout": int(os.environ.get("SQLITE_TIMEOUT", "30")),
            },
        }
    }
else:
    if DB_ENGINE not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured(
            f"Unsupported DB_ENGINE={DB_ENGINE!r}; expected sqlite or postgresql."
        )

    postgres_password = os.environ.get("POSTGRES_PASSWORD", "").strip()
    if not DEBUG and not postgres_password:
        raise ImproperlyConfigured(
            "POSTGRES_PASSWORD must be set when DJANGO_DEBUG=false."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "kormic"),
            "USER": os.environ.get("POSTGRES_USER", "kormic"),
            "PASSWORD": postgres_password or "kormic",
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
        }
    }


# See kormic_backend/test_runner.py: pure_multi_agent.runtime's checkpointer
# pool is a separate psycopg v3 connection outside django.db.connections, so
# it must be closed explicitly before `manage.py test` drops the test
# database, or teardown fails with "database is being accessed by other
# users" on every run after the first.
TEST_RUNNER = "kormic_backend.test_runner.KormicTestRunner"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Served by whitenoise (see MIDDLEWARE) directly from the app process --
# no separate nginx/CDN needed for the admin site's CSS/JS to work in
# production. `manage.py collectstatic` runs on every container start (see
# docker-compose.yml's `web` command), so this is a no-op if nothing changed.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "uploads"

# Institute roster source files contain PII. Reject large uploads before the
# view reads them and remove the raw source after the retention window. Parsed
# roster rows remain in the database according to the application's records
# policy; these settings govern only the original uploaded CSV.
INSTITUTE_ROSTER_MAX_UPLOAD_BYTES = int(
    os.environ.get("INSTITUTE_ROSTER_MAX_UPLOAD_BYTES", str(2 * 1024 * 1024))
)
INSTITUTE_ROSTER_SOURCE_RETENTION_DAYS = int(
    os.environ.get("INSTITUTE_ROSTER_SOURCE_RETENTION_DAYS", "30")
)

# Kormic Django REST API settings
# Cookie authentication requires an explicit origin allow-list, even in development.
CORS_ALLOW_ALL_ORIGINS = False
_local_origins = ','.join(
    f'http://{host}:{port}' for host in ('localhost', '127.0.0.1')
    for port in (5173, 5174, 5175, 8081)
) if DEBUG else ''
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in (os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', '').strip() or _local_origins).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "accounts.exceptions.auth_exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "accounts.permissions.IsTOTPEnrolled",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "auth": "60/min",
        "password_reset": "10/min",
        # claim/start and claim/verify are public by design (the OTP is
        # the auth), so both get an independent per-IP and per-email budget.
        # verify has no outbound email, so it can afford a looser IP rate.
        "claim_start_ip": "10/min",
        "claim_start_email": "3/min",
        "claim_verify_ip": "20/min",
        "claim_verify_email": "10/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Development must not require Redis or Docker. When DEBUG=True, use
# Django's in-process cache so authentication throttles, TOTP replay/lockout
# state, and other cache-backed development flows continue to work without a
# separate service. Production keeps Redis because it is shared across
# gunicorn workers; LocMemCache is deliberately development-only.
if DEBUG or TESTING:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "kormic-development-cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ.get("DJANGO_CACHE_URL", "redis://localhost:6379/2"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }


# Celery -- background delivery for push notifications (see notifications/).
# Chat/agent processing itself stays synchronous: a student's app is waiting
# on the HTTP response for their reply, so there's no natural place to hand
# the turn off to a background worker without also building a poll/push
# mechanism on the client. pure_multi_agent.runtime's LangGraph checkpointer
# is durable and shared (Postgres-backed, not in-process) precisely so this
# synchronous-per-request model is safe to run behind more than one gunicorn
# worker -- see pure_multi_agent/runtime.py's _build_checkpointer(). Celery
# is used for the "send this push" side-effect, which is safely
# fire-and-forget, plus other genuinely background jobs (see
# institutes_list/tasks.py, universities/tasks.py).

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Global defaults, sized for quick tasks (push notifications). Anything that
# legitimately runs longer (url_discovery's crawl, notifications' proactive
# check-in batches) sets its own explicit soft_time_limit/time_limit on the
# @shared_task decorator -- see url_discovery/tasks.py and
# notifications/tasks.py. SOFT_TIME_LIMIT raises a catchable
# SoftTimeLimitExceeded 5s before the hard SIGKILL, so any future task that
# forgets to override still gets one chance to log/clean up instead of
# vanishing silently mid-loop.
CELERY_TASK_TIME_LIMIT = 30
CELERY_TASK_SOFT_TIME_LIMIT = 25
# Run Celery tasks synchronously during local development so starting the
# Django server does not also require Redis, a Celery worker, or Docker.
# Production remains asynchronous unless explicitly overridden.
CELERY_TASK_ALWAYS_EAGER = TESTING or (
    os.environ.get("CELERY_TASK_ALWAYS_EAGER", "true" if DEBUG else "false").lower() == "true"
)
CELERY_TASK_EAGER_PROPAGATES = TESTING

# Proactive agent outreach (notifications.tasks.run_proactive_checkins_task):
# once a day, the agent scans for students it hasn't nudged in
# PROACTIVE_CHECKIN_COOLDOWN_DAYS and, if their profile has a genuine gap
# worth mentioning, messages them on its own. Requires a `celery beat`
# process running alongside the worker -- see notifications/proactive.py.
PROACTIVE_CHECKIN_HOUR = int(os.environ.get("PROACTIVE_CHECKIN_HOUR", "9"))
PROACTIVE_CHECKIN_COOLDOWN_DAYS = int(os.environ.get("PROACTIVE_CHECKIN_COOLDOWN_DAYS", "7"))
# Students per fanned-out Celery sub-task (see run_proactive_checkins_task in
# notifications/tasks.py) -- keeps each sub-task's synchronous DB loop well
# under its own time limit and lets pushes for the whole batch go out as ~1
# Expo call instead of 1-per-student.
PROACTIVE_CHECKIN_BATCH_SIZE = int(os.environ.get("PROACTIVE_CHECKIN_BATCH_SIZE", "50"))

CELERY_BEAT_SCHEDULE = {
    "purge-expired-institute-roster-files": {
        "task": "institutes_list.tasks.purge_expired_source_files",
        "schedule": crontab(hour=3, minute=0),
    },
    "proactive-agent-checkins": {
        "task": "notifications.tasks.run_proactive_checkins_task",
        "schedule": crontab(hour=PROACTIVE_CHECKIN_HOUR, minute=0),
    },
    # See pure_multi_agent.tasks.check_agent_recovery_task: runs every few
    # minutes but only ever costs a Redis read unless an outage is actually
    # flagged, so this cadence doesn't translate into real LLM spend.
    "agent-recovery-check": {
        "task": "pure_multi_agent.tasks.check_agent_recovery_task",
        "schedule": crontab(minute="*/5"),
    },
    "cleanup-old-audit-logs": {
        "task": "django_api.tasks.cleanup_old_audit_logs_task",
        "schedule": crontab(hour=2, minute=0),  # Run nightly at 2:00 AM
    },
}

# Expo push notifications (student mobile app).
EXPO_PUSH_ACCESS_TOKEN = os.environ.get("EXPO_PUSH_ACCESS_TOKEN", "")

# Email configuration -- used to deliver password-reset OTP codes (see
# accounts.email) and claim-invite emails (institutes_list.tasks).
# dev → Ethereal only; no real emails sent.
# prod → Real SMTP only; no Ethereal.
# dual → Ethereal + real SMTP for non-test domains.
# Default → dev when DEBUG=True, otherwise prod.
# prod/dual → Require all real SMTP settings; missing values cause startup failure.
EMAIL_MODE = os.getenv("EMAIL_MODE", "dev" if DEBUG else "prod").lower()

FAKE_EMAIL_DOMAINS = {
    d.strip().lower()
    for d in os.getenv(
        "FAKE_EMAIL_DOMAINS", "test.com,example.com,example.net,example.org,test,invalid,localhost"
    ).split(",")
    if d.strip()
}


def _require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise ImproperlyConfigured(f"{name} must be set (non-empty) when EMAIL_MODE={EMAIL_MODE!r}.")
    return value


# Ethereal (sandbox) connection -- used by "dev" and "dual". Host/port/TLS
# default to Ethereal's own public SMTP endpoint so only the per-inbox
# ETHEREAL_HOST_USER/PASSWORD (from https://ethereal.email) need setting.
ETHEREAL_HOST = os.getenv("ETHEREAL_HOST", "smtp.ethereal.email")
ETHEREAL_PORT = int(os.getenv("ETHEREAL_PORT", "587"))
ETHEREAL_USE_TLS = os.getenv("ETHEREAL_USE_TLS", "true").lower() == "true"
ETHEREAL_USE_SSL = os.getenv("ETHEREAL_USE_SSL", "false").lower() == "true"

if EMAIL_MODE == "dev":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = ETHEREAL_HOST
    EMAIL_PORT = ETHEREAL_PORT
    EMAIL_USE_TLS = ETHEREAL_USE_TLS
    EMAIL_USE_SSL = ETHEREAL_USE_SSL
    EMAIL_HOST_USER = os.getenv("ETHEREAL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("ETHEREAL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "test@example.com")
elif EMAIL_MODE == "prod":
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = _require_env("EMAIL_HOST")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
    EMAIL_HOST_USER = _require_env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = _require_env("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = _require_env("DEFAULT_FROM_EMAIL")
elif EMAIL_MODE == "dual":
    EMAIL_BACKEND = "kormic_backend.email_backends.DualSendEmailBackend"
    EMAIL_HOST = _require_env("EMAIL_HOST")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
    EMAIL_HOST_USER = _require_env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = _require_env("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = _require_env("DEFAULT_FROM_EMAIL")
    ETHEREAL_HOST_USER = _require_env("ETHEREAL_HOST_USER")
    ETHEREAL_HOST_PASSWORD = _require_env("ETHEREAL_HOST_PASSWORD")
else:
    raise ImproperlyConfigured(f"Unknown EMAIL_MODE={EMAIL_MODE!r}; expected 'dev', 'prod', or 'dual'.")

# Who gets emailed when the student agent starts failing (e.g. Anthropic
# credit exhaustion) and again once it recovers -- see
# extra_utils.send_mail_to_superuser and pure_multi_agent.tasks. Comma-
# separated; empty means no one is notified (a warning is logged instead).
AGENT_ALERT_EMAILS = [
    addr.strip() for addr in os.getenv("AGENT_ALERT_EMAILS", "").split(",") if addr.strip()
]

# Student frontend/deep-link destination for invite emails, not the Django API.
# Set https://app.kormic.ai/claim after deploying the public app-link domain;
# the backend appends ?token=... (see APP_LINKS.md). Configure the backend and
# Celery worker, not the portal frontends. Leave unset until that page is ready:
# institutes_list.views.send_invites intentionally fails rather than emailing
# an unconfigured destination.
CLAIM_PAGE_URL = os.getenv("CLAIM_PAGE_URL", "")

# Served on app.kormic.ai by the dedicated proxy in deploy/app-links.nginx.conf.
# Use the Play app-signing certificate (not merely the upload certificate).
APP_LINK_ANDROID_SHA256_FINGERPRINTS = [
    value.strip() for value in os.getenv('APP_LINK_ANDROID_SHA256_FINGERPRINTS', '').split(',')
    if value.strip()
]
# The prefix from the signed iOS application's application-identifier entitlement.
# Usually the Apple Team ID; older accounts can have a different App ID prefix.
APP_LINK_APPLE_APP_ID_PREFIX = os.getenv('APP_LINK_APPLE_APP_ID_PREFIX', '').strip()
APP_LINK_ANDROID_STORE_URL = os.getenv('APP_LINK_ANDROID_STORE_URL', '').strip()
APP_LINK_IOS_STORE_URL = os.getenv('APP_LINK_IOS_STORE_URL', '').strip()


# Logging -- without this, Django/Celery's default logging goes essentially
# nowhere useful in production. Everything goes to stdout/stderr (the
# standard practice for containers: `docker logs`, and whatever log driver
# / CloudWatch agent the host has configured picks it up from there) rather
# than a file path this app would have to manage permissions/rotation for.
# DJANGO_LOG_LEVEL defaults to INFO so a bare production deploy gets useful
# output immediately; tighten with an env var if it's too chatty.
LOG_LEVEL = os.environ.get("DJANGO_LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {

        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
