# Generated by Django 5.2.15 on 2026-09-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=255)),
                ('student_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('actor_agent', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student_id', '-timestamp'], name='django_api__student_90994f_idx')],
            },
        ),
    ]
