# Generated by Django 5.2.15 on 2026-09-18 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_agentauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGate',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, max_length=100)),
                ('message_id', models.BigIntegerField(null=True)),
                ('edit', models.BooleanField(default=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('latency_ms', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.chatgate')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.chatgeneration')),
            ],
        ),
        migrations.CreateModel(
            name='ChatModelCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('input_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField(null=True)),
                ('charged_tokens', models.PositiveIntegerField()),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_calls', to='django_api.chatgeneration')),
            ],
        ),
    ]
