# Generated by Django 5.2.17 on 2026-09-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_agentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentidentity',
            name='ain',
            field=models.CharField(blank=True, help_text='MeshKor Cryptographic Identity', max_length=120, null=True),
        ),
    ]
