# Generated by Django 5.2.15 on 2026-09-18 13:35

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension

def create_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE INDEX knowledge_embedding_hnsw ON django_api_knowledgechunk USING hnsw (embedding vector_cosine_ops) WITH (m=16, ef_construction=64)")

def drop_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS knowledge_embedding_hnsw")

def date_existing_verifications(apps, schema_editor):
    from django.db.models import F
    apps.get_model("django_api", "UniversityKnowledgeEntry").objects.filter(source_type__in=["human_verified", "verified"], last_verified_at__isnull=True).update(last_verified_at=F("created_at"))



class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_chatgate_chatgeneration_chatlease_chatmodelcall'),
        ('universities', '0002_staffauditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='global', max_length=120, unique=True)),
                ('upload_days', models.PositiveIntegerField(default=365)),
                ('transcript_days', models.PositiveIntegerField(default=180)),
                ('memory_days', models.PositiveIntegerField(default=180)),
                ('verification_days', models.PositiveIntegerField(default=365)),
                ('notification_days', models.PositiveIntegerField(default=90)),
                ('roster_days', models.PositiveIntegerField(default=365)),
                ('telemetry_days', models.PositiveIntegerField(default=90)),
                ('inactive_account_days', models.PositiveIntegerField(default=730)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatgeneration',
            name='account_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chatgeneration',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chatgeneration',
            name='tool_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatgeneration',
            name='university_fanout',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmodelcall',
            name='account_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chatmodelcall',
            name='actual_cost_usd',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='chatmodelcall',
            name='error_category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='chatmodelcall',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='universityknowledgeentry',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='universityknowledgeentry',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmodelcall',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_calls', to='django_api.chatgeneration'),
        ),
        migrations.CreateModel(
            name='StudentDeletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('not_before', models.DateTimeField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('embedded_at', models.DateTimeField(null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='django_api.universityknowledgeentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entry', 'ordinal'), name='unique_entry_chunk')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('health', models.CharField(db_index=True, default='pending', max_length=30)),
                ('last_fetched_at', models.DateTimeField(null=True)),
                ('last_success_at', models.DateTimeField(null=True)),
                ('changed_at', models.DateTimeField(null=True)),
                ('next_fetch_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(null=True)),
                ('stale_days', models.PositiveIntegerField(default=30)),
                ('recrawl_hours', models.PositiveIntegerField(default=24)),
                ('http_status', models.PositiveIntegerField(null=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='universities.university')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('university', 'url'), name='unique_university_source')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_index, drop_index)],
            state_operations=[migrations.AddIndex(model_name="knowledgechunk", index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=["embedding"], m=16, name="knowledge_embedding_hnsw", opclasses=["vector_cosine_ops"]))],
        ),
        migrations.RunPython(date_existing_verifications, migrations.RunPython.noop),
    ]
