# Generated by Django 5.2.17 on 2026-09-24 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_university_knowledge_vectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentQueueGate',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeIndexWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.CharField(max_length=255, unique=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('indexed_revision', models.PositiveBigIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_key', models.CharField(max_length=300)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=30)),
                ('student_id', models.CharField(blank=True, max_length=255)),
                ('university_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('dispatched_at', models.DateTimeField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='agent_job_dispatch')],
                'constraints': [models.UniqueConstraint(fields=('owner_key', 'idempotency_key'), name='agent_job_idempotency'), models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'processing'])), fields=('owner_key',), name='agent_one_active_turn')],
            },
        ),
    ]
