# Generated by Django 5.2.15 on 2026-09-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_retentionpolicy_chatgeneration_account_id_and_more'),
        ('universities', '0002_staffauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.knowledgegroup'),
        ),
    ]
