# Generated by Django 5.2.17 on 2026-09-26 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encrypt_totp_secrets'),
        ('django_api', '0005_retrieval_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField()),
                ('identity', models.JSONField(default=dict)),
                ('statistics', models.JSONField(default=dict)),
                ('languages', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('technologies', models.JSONField(default=list)),
                ('domains', models.JSONField(default=list)),
                ('organizations', models.JSONField(default=list)),
                ('recent_activity', models.JSONField(default=list)),
                ('academic_guidance', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('summary_kind', models.CharField(default='factual', max_length=32)),
                ('coverage', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='accounts.githuboauthconnection')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_snapshot', to='django_api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=500)),
                ('owner_login', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=False)),
                ('fork', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('languages', models.JSONField(default=dict)),
                ('readme', models.TextField(blank=True)),
                ('readme_url', models.URLField(blank=True, max_length=1200)),
                ('readme_truncated', models.BooleanField(default=False)),
                ('details_complete', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='django_api.githubprofilesnapshot')),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GitHubRepositoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('analysis_version', models.PositiveIntegerField(default=2)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='django_api.githubrepository')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubSourceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=1600)),
                ('excerpt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_evidence', to='django_api.githubrepository')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('progress', models.CharField(default='Waiting to collect GitHub profile', max_length=300)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='django_api.githubprofilesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='githubrepository',
            index=models.Index(fields=['profile', 'active', 'full_name'], name='github_repo_page'),
        ),
        migrations.AddConstraint(
            model_name='githubrepository',
            constraint=models.UniqueConstraint(fields=('profile', 'github_id'), name='github_repo_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='githubrepositoryreport',
            constraint=models.UniqueConstraint(fields=('repository', 'sha', 'analysis_version'), name='github_report_at_commit'),
        ),
        migrations.AddConstraint(
            model_name='githubsourceevidence',
            constraint=models.UniqueConstraint(fields=('repository', 'sha', 'path'), name='github_source_at_commit'),
        ),
        migrations.AddConstraint(
            model_name='githubsyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('profile',), name='one_active_github_sync'),
        ),
    ]
