# Generated by Django 5.2.15 on 2026-09-18 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_knowledgesource_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='memory_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
