# Generated by Django 5.2.17 on 2026-09-26 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0006_github_profile_extraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubModelPool',
            fields=[
                ('provider', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('blocked_until', models.DateTimeField(null=True)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='available_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='model_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='reserved_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='stage',
            field=models.CharField(default='collect', max_length=20),
        ),
        migrations.AddField(
            model_name='githubsyncrun',
            name='work',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='GitHubAgentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.CharField(max_length=180)),
                ('namespace', models.CharField(default='', max_length=180)),
                ('checkpoint_id', models.CharField(max_length=64)),
                ('parent_id', models.CharField(blank=True, max_length=64)),
                ('payload_type', models.CharField(max_length=32)),
                ('payload', models.BinaryField()),
                ('metadata', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='django_api.githubsyncrun')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubAgentWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64)),
                ('index', models.IntegerField()),
                ('channel', models.CharField(max_length=100)),
                ('payload_type', models.CharField(max_length=32)),
                ('payload', models.BinaryField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='django_api.githubagentcheckpoint')),
            ],
        ),
        migrations.CreateModel(
            name='GitHubModelSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField()),
                ('token', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'number'), name='github_model_slot_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='githubagentcheckpoint',
            constraint=models.UniqueConstraint(fields=('run', 'thread', 'namespace', 'checkpoint_id'), name='github_agent_checkpoint_unique'),
        ),
        migrations.AddConstraint(
            model_name='githubagentwrite',
            constraint=models.UniqueConstraint(fields=('checkpoint', 'task_id', 'index'), name='github_agent_write_unique'),
        ),
    ]
