# Generated by Django 5.2.17 on 2026-09-26 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0007_github_agent_queue'),
        ('universities', '0005_university_country_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentChangeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('operation', models.CharField(max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('turn_id', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('assumption_active', models.BooleanField(default=False)),
                ('source_message', models.TextField()),
                ('resolution_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_api.studentprofile')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['student', 'status'], name='proposal_student_status'), models.Index(fields=['university', 'actor', 'status'], name='proposal_officer_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'student_profile'), ('student__isnull', False), ('university__isnull', True)), models.Q(('kind__in', ['university_profile', 'university_knowledge']), ('student__isnull', True), ('university__isnull', False)), _connector='OR'), name='proposal_has_one_scope')],
            },
        ),
    ]
