# Generated by Django 5.2.17 on 2026-09-26 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0008_agent_change_proposals'),
        ('universities', '0005_university_country_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocumentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=150)),
                ('source_type', models.CharField(blank=True, max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted', models.JSONField(default=dict)),
                ('status', models.CharField(default='read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='agentchangeproposal',
            name='proposal_has_one_scope',
        ),
        migrations.AddConstraint(
            model_name='agentchangeproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['student_profile', 'student_document']), ('student__isnull', False), ('university__isnull', True)), models.Q(('kind__in', ['university_profile', 'university_knowledge']), ('student__isnull', True), ('university__isnull', False)), _connector='OR'), name='proposal_has_one_scope'),
        ),
        migrations.AddField(
            model_name='studentdocumentevidence',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api.chatattachment'),
        ),
        migrations.AddField(
            model_name='studentdocumentevidence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_documents', to='django_api.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='studentdocumentevidence',
            index=models.Index(fields=['student', 'source_type', 'status'], name='student_document_source'),
        ),
    ]
