# Generated by Django 5.2.17 on 2026-09-26 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0009_student_document_evidence'),
        ('universities', '0005_university_country_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentchangeproposal',
            name='proposal_has_one_scope',
        ),
        migrations.AddField(
            model_name='universityknowledgeentry',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='agentchangeproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['student_profile', 'student_document']), ('student__isnull', False), ('university__isnull', True)), models.Q(('kind__in', ['university_profile', 'university_knowledge', 'university_group']), ('student__isnull', True), ('university__isnull', False)), _connector='OR'), name='proposal_has_one_scope'),
        ),
    ]
