# Generated by Django 5.2.17 on 2026-09-28 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0010_university_policy_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceWaiter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=300)),
                ('rank_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'rank_at'], name='inference_wait_order')],
            },
        ),
    ]
