# Generated by Django 5.2.17 on 2026-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0011_inference_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentjob',
            name='execution_token',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='heartbeat_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='recovery_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='recovery_phase',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='inferencewaiter',
            name='priority',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inferencewaiter',
            name='tenant',
            field=models.CharField(default='legacy', max_length=300),
        ),
        migrations.CreateModel(
            name='InferenceTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('tenant', models.CharField(max_length=300)),
                ('last_served_at', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'tenant'), name='inference_tenant_unique')],
            },
        ),
    ]
