# Generated by Django 5.2.17 on 2026-10-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0013_merge_meshkor_main_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentidentity',
            name='ain',
            field=models.CharField(blank=True, help_text='MeshKor Cryptographic Identity', max_length=255, null=True),
        ),
    ]
