# Generated by Django 5.2.17 on 2026-09-28 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes_list', '0008_invitation_delivery_lease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimCodeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField(default=uuid.uuid4)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes_list.listedstudent')),
            ],
        ),
    ]
