# Generated by Django 5.2.15 on 2026-09-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encrypt_totp_secrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='onboarding_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='university_role',
            field=models.CharField(choices=[('owner', 'University Owner/Admin'), ('admissions', 'Admissions'), ('international', 'International Office'), ('financial_aid', 'Financial Aid'), ('campus_life', 'Campus Life'), ('viewer', 'Viewer/Auditor')], default='owner', max_length=30),
        ),
    ]
