# Generated by Django 5.2.15 on 2026-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_onboarding_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_active_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
