# Generated by Django 5.2.17 on 2026-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_github_oauth_telemetry'),
        ('universities', '0006_remove_university_university_country_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='staff_accounts', to='universities.knowledgegroup'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('university', 'University'), ('department', 'Department staff'), ('institute', 'Institute'), ('superuser', 'Superuser')], max_length=20),
        ),
    ]
