# Generated by Django 5.2.17 on 2026-10-03 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_departments_alter_account_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFaceChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_jti', models.CharField(db_index=True, max_length=64)),
                ('sequence', models.JSONField(default=list)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('encrypted_reference', models.BinaryField(default=bytes)),
                ('capture_hashes', models.JSONField(default=list)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step_started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('passed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFaceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_template', models.BinaryField()),
                ('model_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
