# Generated by Django 5.2.17 on 2026-09-26 08:43

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_api', '0007_github_agent_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUniversity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=400)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(max_length=1000)),
                ('discovery_sources', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(db_index=True, null=True)),
                ('coverage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisingArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('content', models.JSONField(default=dict)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_artifacts', to='django_api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InformationPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('refresh_days', models.PositiveSmallIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('progress', models.CharField(default='Waiting to research the official website', max_length=300)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('state', models.JSONField(default=dict)),
                ('steps', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='university_research.publicuniversity')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university_research.researchrun')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='university_research.publicuniversity')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=400)),
                ('term', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('deadline', models.CharField(blank=True, max_length=300)),
                ('applicant_scope', models.CharField(blank=True, max_length=300)),
                ('source_quote', models.TextField()),
                ('fetched_at', models.DateTimeField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='university_research.publicuniversity')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_research.universitypage')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_quote', models.TextField()),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='university_research.publicuniversity')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_research.universitypage')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=150)),
                ('study_mode', models.CharField(blank=True, max_length=150)),
                ('tuition', models.CharField(blank=True, max_length=500)),
                ('currency', models.CharField(blank=True, max_length=20)),
                ('requirements', models.TextField(blank=True)),
                ('source_quote', models.TextField()),
                ('fetched_at', models.DateTimeField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university_research.publicuniversity')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_research.universitypage')),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('candidates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.studentprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['status', 'available_at'], name='research_dispatch'),
        ),
        migrations.AddConstraint(
            model_name='researchrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('university',), name='research_one_active'),
        ),
        migrations.AddConstraint(
            model_name='universitypage',
            constraint=models.UniqueConstraint(fields=('university', 'url'), name='research_unique_page'),
        ),
    ]
