# Generated by Django 5.2.17 on 2026-09-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_country_default'),
        ('university_research', '0002_vector_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuniversity',
            name='registered_university',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_research', to='universities.university'),
        ),
    ]
