# Generated by Django 5.2.17 on 2026-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_research', '0003_publicuniversity_registered_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycourse',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='seats',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='universitypage',
            name='provider',
            field=models.CharField(default='scraper', max_length=40),
        ),
    ]
