# Generated by Django 5.2.17 on 2026-09-30 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0012_agent_fairness_recovery'),
        ('university_research', '0004_universitycourse_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonAgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('kind', models.CharField(default='message', max_length=30)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.studentprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_research.publicuniversity')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'university', '-created_at'], name='common_agent_history')],
            },
        ),
    ]
