# Generated by Django 5.2.17 on 2026-10-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_research', '0005_common_agent_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPageExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=100)),
                ('instructions_version', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=150)),
                ('result', models.JSONField()),
                ('source_url', models.URLField(max_length=1000)),
                ('retrieved_at', models.DateTimeField()),
                ('supporting_excerpts', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_hash', 'schema_version', 'instructions_version', 'model_version'), name='unique_public_extraction_version')],
            },
        ),
    ]
