# Generated by Django 5.2.17 on 2026-10-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_research', '0006_publicpageextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=64)),
                ('scope', models.JSONField(default=dict)),
                ('status', models.CharField(default='running', max_length=16)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_jobs', to='university_research.publicuniversity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('university', 'scope_key'), name='unique_public_collection_scope')],
            },
        ),
    ]
