"""Native LangChain tool calling, Qwen first and Claude on provider failure.

The DB provider pools are shared with GitHub extraction across all processes.
Capacity exhaustion is backpressure, never an unbounded burst of paid fallback.
"""
import logging
import os
import time
from contextlib import contextmanager, ExitStack
from functools import lru_cache
from urllib.parse import urlsplit

import httpx
from langchain_anthropic import ChatAnthropic
from langchain_ollama import ChatOllama
from django.conf import settings
from github_profiles.scheduling import model_slot, provider_blocked, block_provider, CapacityBusy

logger = logging.getLogger(__name__)


class AIServiceUnavailable(RuntimeError):
    pass


@contextmanager
def qwen_slot(estimate):
    """Wait briefly for local inference without replaying model/tool execution."""
    deadline = time.monotonic() + 20
    while True:
        stack = ExitStack()
        try:
            stack.enter_context(model_slot('qwen', None, estimate))
        except CapacityBusy:
            stack.close()
            if time.monotonic() >= deadline:
                raise
            from pure_multi_agent.activity import publish
            publish('Waiting for the local AI to become availableÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¦')
            time.sleep(1)
            continue
        with stack:
            yield
        return


def provider_messages(messages, provider, model_name):
    """Supply actual dispatch identity, never identity inferred from chat history."""
    from langchain_core.messages import SystemMessage
    identity = (f'\nRUNTIME MODEL IDENTITY: This response is generated by {provider}, model {model_name}. '
        + ('Qwen is developed by Alibaba Cloud. You are not Claude on this call. '
           if provider == 'Qwen' else 'Claude is developed by Anthropic. You are serving as the fallback provider on this call. ')
        + 'When asked which model you are, answer using this runtime identity. '
        'Earlier assistant claims about its model may be incorrect or from another provider; do not repeat them. '
        'Your configured assistant name is separate from your underlying model.')
    # Anthropic requires one leading system instruction. Keep conversation/tool
    # order intact while combining application-generated system instructions.
    blocks = []
    conversation = []
    for message in messages:
        if message.type == 'system':
            blocks.extend([{'type': 'text', 'text': message.content}]
                          if isinstance(message.content, str) else message.content)
        else:
            conversation.append(message)
    if all(block.get('type') == 'text' for block in blocks):
        content = '\n\n'.join(block['text'] for block in blocks) + identity
    else:
        content = [*blocks, {'type': 'text', 'text': identity}]
    return [SystemMessage(content=content), *conversation]


@lru_cache(maxsize=1)
def qwen():
    base = os.getenv('STUDENT_OLLAMA_BASE_URL', settings.GITHUB_OLLAMA_BASE_URL).rstrip('/')
    if urlsplit(base).hostname not in settings.GITHUB_OLLAMA_ALLOWED_HOSTS:
        raise ValueError('Ollama host is not in the configured allowlist')
    return ChatOllama(model=os.getenv('STUDENT_OLLAMA_MODEL', settings.GITHUB_OLLAMA_MODEL),
        base_url=base, temperature=0, reasoning=False, num_ctx=16384, num_predict=2400, keep_alive=-1,
        client_kwargs={'timeout': httpx.Timeout(90, connect=2), 'trust_env': False})


@lru_cache(maxsize=1)
def claude():
    return ChatAnthropic(model=os.getenv('STUDENT_CLAUDE_MODEL', 'claude-haiku-4-5-20251001'),
        max_tokens=6000, timeout=90, max_retries=0)


def _validate(reply, tools, *, validate_arguments=True, require_tools=False):
    if reply.invalid_tool_calls:
        raise ValueError('Malformed model tool call')
    mapping = {t.name: t for t in tools}
    if len(reply.tool_calls) > 6:
        raise ValueError('Too many parallel tool calls')
    for call in reply.tool_calls:
        if call['name'] not in mapping:
            raise ValueError('Unknown model tool')
        if validate_arguments:
            mapping[call['name']].args_schema.model_validate(call['args'])
    if not reply.tool_calls and not reply.content:
        raise ValueError('Empty model response')
    if require_tools and not reply.tool_calls:
        raise ValueError('This workflow step requires a tool call before a final response')
    return reply


def invoke(messages, tools=(), *, force_claude=False, require_tools=False, json_schema=None):
    try:
        from agents.meshkor_client import meshkor_client
        import meshkor.integrations.kormic
        meshkor.integrations.kormic.NETWORK_TIMEOUT_SEC = 5.0
        for m in messages:
            if getattr(m, 'type', '') == 'human':
                c = str(m.content) if not isinstance(m.content, str) else m.content
                if len(c) > 0:
                    ain_val = __import__('agents.meshkor_client', fromlist=['current_ain']).current_ain.get()
                    if ain_val: meshkor_client.record_event(ain_val,
                        event_description="[MESHKOR SDK] TRIPWIRE: Evaluating inference request.",
                        event_data={"prompt": c[:100]}
                    )
    except Exception as e:
        pass
    # Text-only Qwen cannot interpret an uploaded image. Claude can.
    vision = any(isinstance(m.content, list) and any(isinstance(b, dict) and b.get('type') in ('image', 'image_url', 'document') for b in m.content) for m in messages)
    def token_estimate(content):
        if isinstance(content, list):
            # Base64 bytes are transport, not text tokens. Reserve a conservative
            # vision/document allowance without creating an impossible queue job.
            return sum(16000 if isinstance(b, dict) and b.get('type') == 'document' else
                6000 if isinstance(b, dict) and b.get('type') in ('image', 'image_url') else len(str(b)) // 3 for b in content)
        return len(str(content)) // 3
    estimate = max(1500, sum(token_estimate(m.content) for m in messages) + sum(len(str(t.args)) for t in tools) // 3 + 6000)
    local_busy = False
    if not (force_claude or vision or provider_blocked('qwen')):
        try:
            with qwen_slot(estimate):
                model = qwen().bind_tools(tools) if tools else qwen()
                if json_schema is not None:
                    model = model.bind(format=json_schema)
                current_messages = provider_messages(messages, 'Qwen', qwen().model)
                reply = model.invoke(current_messages)
                if require_tools and not reply.tool_calls:
                    # Small models can echo stale assistant history instead of
                    # retrieving. Give Qwen one bounded retry before fallback.
                    from langchain_core.messages import HumanMessage
                    last_human = max((i for i, m in enumerate(messages) if m.type == 'human'), default=1)
                    retry = [current_messages[0], *messages[last_human:], HumanMessage(content=
                        'Call the relevant available tool now. Do not repeat earlier answers. Return a tool call, not a promise or final answer.')]
                    reply = model.invoke(retry)
                reply = _validate(reply, tools, require_tools=require_tools)
                if json_schema is not None:
                    import json
                    import jsonschema
                    jsonschema.validate(json.loads(reply.content), json_schema)
                reply.response_metadata['routing_provider'] = 'qwen'
                reply.response_metadata['routing_model'] = qwen().model
                logger.info('AI response provider=qwen model=%s tool_calls=%s', qwen().model, len(reply.tool_calls))
                return reply
        except CapacityBusy:
            # Queue pressure is not a provider failure. The graph checkpoints
            # and resumes instead of turning a traffic spike into paid calls.
            raise
        except Exception as exc:
            if getattr(exc, 'status_code', None) in (429, 503):
                raise CapacityBusy('Qwen is busy', 5) from exc
            # A malformed answer is specific to this prompt; do not disable
            # healthy Qwen for every other user's request for a minute.
            if not isinstance(exc, ValueError):
                block_provider('qwen', 60)
            logger.info('Qwen unavailable or invalid tool response; using Claude (%s)', type(exc).__name__)
    if provider_blocked('claude'):
        if local_busy:
            raise CapacityBusy('Local AI is busy; retry shortly.', 5)
        raise AIServiceUnavailable('The AI service is unavailable. The administrator needs to check the backup AI credentials.')
    with model_slot('claude', None, estimate):
        try:
            from pure_multi_agent.capacity import model_slot as distributed_claude_slot
            with distributed_claude_slot():
                model = claude().bind_tools(tools, **({'tool_choice': 'any'} if require_tools else {})) if tools else claude()
                # LangChain tools validate arguments before execution. Return
                # errors to Claude through the graph so it can repair a call.
                current_messages = provider_messages(messages, 'Claude', claude().model)
                reply = model.invoke(current_messages)
                try:
                    reply = _validate(reply, tools, validate_arguments=False, require_tools=require_tools)
                except ValueError:
                    # Retry the model only: no invalid or duplicate tool is executed.
                    from langchain_core.messages import HumanMessage
                    correction = 'Your previous response did not match the available tools. Allowed tools: ' + ', '.join(t.name for t in tools)
                    correction += '. Use only these tools with their declared parameters.' if tools else '. Return a text answer without tool calls.'
                    reply = _validate(model.invoke([*current_messages, HumanMessage(content=correction)]), tools,
                        validate_arguments=False, require_tools=require_tools)
                reply.response_metadata['routing_provider'] = 'claude'
                reply.response_metadata['routing_model'] = claude().model
                logger.info('AI response provider=claude tool_calls=%s', len(reply.tool_calls))
                return reply
        except Exception as exc:
            if getattr(exc, 'status_code', None) in (401, 403):
                block_provider('claude', 60)
                if local_busy:
                    raise CapacityBusy('Local AI is busy; retry shortly.', 5) from exc
                raise AIServiceUnavailable('The AI service is unavailable. The administrator needs to check the backup AI credentials.') from exc
            if getattr(exc, 'status_code', None) in (429, 529):
                raise CapacityBusy('Claude is busy', 15) from exc
            raise
