"""Native LangChain tool calling through Claude only.

The DB provider pools are shared with GitHub extraction across all processes.
Capacity exhaustion is backpressure, never an unbounded burst of paid fallback.
"""
import logging
from pure_multi_agent.model_usage import measured_invoke
import json
from pydantic import ValidationError
import os
import time
from contextlib import contextmanager, ExitStack
from functools import lru_cache
from urllib.parse import urlsplit

import httpx
from langchain_anthropic import ChatAnthropic
from langchain_ollama import ChatOllama
from django.conf import settings
from github_profiles.scheduling import model_slot, provider_blocked, block_provider, CapacityBusy
from kormic_backend.ollama_config import qwen_keep_alive, QWEN_REQUEST_TIMEOUT_SECONDS
from pure_multi_agent.qwen_context import select_context, needs_expansion, ContextBudgetExceeded
from pure_multi_agent.reservations import reservation_estimate, claude_output_allowance

logger = logging.getLogger(__name__)


class AIServiceUnavailable(RuntimeError):
    pass


class InvalidToolResponse(AIServiceUnavailable):
    pass


class InvalidLocalToolResponse(InvalidToolResponse):
    pass


from contextvars import ContextVar
from functools import wraps
_student_execution = ContextVar('student_model_policy', default=False)


def student_model_policy(fn):
    @wraps(fn)
    def wrapped(*args, **kwargs):
        token = _student_execution.set(True)
        try:
            return fn(*args, **kwargs)
        finally:
            _student_execution.reset(token)
    return wrapped


def advice_options():
    """All reasoning uses Claude; website extraction does not call this router."""
    return {'force_claude': True}


@contextmanager
def qwen_slot(estimate):
    """Wait briefly for local inference without replaying model/tool execution."""
    deadline = time.monotonic() + 20
    while True:
        stack = ExitStack()
        try:
            stack.enter_context(model_slot('qwen', None, estimate))
        except CapacityBusy:
            stack.close()
            if time.monotonic() >= deadline:
                raise
            from pure_multi_agent.activity import publish
            publish('Waiting for the local AI to become available…')
            time.sleep(1)
            continue
        with stack:
            yield
        return


def provider_messages(messages, provider, model_name):
    """Supply actual dispatch identity, never identity inferred from chat history."""
    from langchain_core.messages import SystemMessage
    identity = (f'\nRUNTIME MODEL IDENTITY: This response is generated by {provider}, model {model_name}. '
        + ('Qwen is developed by Alibaba Cloud. You are not Claude on this call. '
           if provider == 'Qwen' else 'Claude is developed by Anthropic. You are the configured inference provider. ')
        + 'When asked which model you are, answer using this runtime identity. '
        'Earlier assistant claims about its model may be incorrect or from another provider; do not repeat them. '
        'Your configured assistant name is separate from your underlying model.')
    # Anthropic requires one leading system instruction. Keep conversation/tool
    # order intact while combining application-generated system instructions.
    blocks = []
    conversation = []
    for message in messages:
        if message.type == 'system':
            blocks.extend([{'type': 'text', 'text': message.content}]
                          if isinstance(message.content, str) else message.content)
        else:
            conversation.append(message)
    if all(block.get('type') == 'text' for block in blocks):
        content = '\n\n'.join(block['text'] for block in blocks) + identity
    else:
        content = [*blocks, {'type': 'text', 'text': identity}]
    return [SystemMessage(content=content), *conversation]


@lru_cache(maxsize=16)
def qwen(num_ctx=16384, num_predict=2400):
    base = os.getenv('STUDENT_OLLAMA_BASE_URL', settings.GITHUB_OLLAMA_BASE_URL).rstrip('/')
    if urlsplit(base).hostname not in settings.GITHUB_OLLAMA_ALLOWED_HOSTS:
        raise ValueError('Ollama host is not in the configured allowlist')
    return ChatOllama(model=os.getenv('STUDENT_OLLAMA_MODEL', settings.GITHUB_OLLAMA_MODEL),
        base_url=base, temperature=0, reasoning=False, num_ctx=num_ctx, num_predict=num_predict,
        keep_alive=qwen_keep_alive(),
        client_kwargs={'timeout': httpx.Timeout(QWEN_REQUEST_TIMEOUT_SECONDS, connect=2), 'trust_env': False})


@lru_cache(maxsize=4)
def claude(max_tokens=6000):
    from pure_multi_agent.claude_policy import model_name
    return ChatAnthropic(model=model_name(),
        max_tokens=max_tokens, timeout=90, max_retries=0)


def _validate(reply, tools, *, validate_arguments=True, require_tools=False):
    if (getattr(reply, 'response_metadata', {}) or {}).get('stop_reason') == 'max_tokens':
        logger.warning('Claude response reached its configured output allowance before completion')
        raise ValueError('The model response was truncated; produce a concise complete answer.')
    if reply.invalid_tool_calls:
        raise ValueError('Malformed model tool call')
    mapping = {t.name: t for t in tools}
    if len(reply.tool_calls) > 6:
        raise ValueError('Too many parallel tool calls')
    for call in reply.tool_calls:
        if call['name'] not in mapping:
            raise ValueError('Unknown model tool')
        if validate_arguments:
            normalize_arguments = getattr(mapping[call['name']].args_schema, 'normalize_call_arguments', None)
            if normalize_arguments:
                call['args'] = normalize_arguments(call['args'])
            mapping[call['name']].args_schema.model_validate(call['args'])
    if not reply.tool_calls and not reply.content:
        raise ValueError('Empty model response')
    if require_tools and not reply.tool_calls:
        raise ValueError('This workflow step requires a tool call before a final response')
    return reply


def _local_repair_instruction(reply, tools, error):
    """Give the local model actionable schema feedback without executing a tool."""
    if isinstance(error, ValidationError):
        details = [{'field': '.'.join(map(str, item['loc'])), 'problem': item['msg']}
                   for item in error.errors(include_input=False, include_url=False)]
    else:
        details = str(error)
    calls = reply.tool_calls or []
    names = {call['name'] for call in calls}
    schemas = {tool.name: tool.args_schema.model_json_schema() for tool in tools if tool.name in names}
    return ('Your last response failed validation and no tool was executed. Correct it locally. '
        'Use the exact declared field names and types; do not invent missing facts, scope, or consent. '
        'If required facts are absent, use a relevant read tool or ask a focused clarification '
        '(after required retrieval). Never claim a rejected operation succeeded. '
        'Allowed tools: ' + ', '.join(tool.name for tool in tools) +
        '\nValidation: ' + json.dumps(details, ensure_ascii=False)[:6000] +
        '\nRejected calls: ' + json.dumps(calls, ensure_ascii=False)[:6000] +
        '\nRelevant schemas: ' + json.dumps(schemas, ensure_ascii=False)[:14000])


def invoke(messages, tools=(), *, force_claude=False, require_tools=False, json_schema=None, tool_call_validator=None, local_only=False, response_validator=None, single_attempt=False, research=False, profile='general', message_preparer=None):
    # Retain legacy keyword compatibility while enforcing the application policy.
    # local_only must not silently route old callers to Ollama.
    claude_limit = claude_output_allowance(profile)
    estimate = reservation_estimate(messages, tools, profile=profile, format_schema=json_schema)
    local_busy = False
    if json_schema is not None:
        from langchain_core.messages import SystemMessage
        from pure_multi_agent.chat_cost_controls import compact_json
        messages = [SystemMessage(content='Return only JSON matching this schema: ' + compact_json(json_schema)), *messages]
    original_validator = response_validator
    def validate_response(reply):
        if original_validator:
            original_validator(reply)
        if json_schema is not None:
            import jsonschema
            raw = reply.content
            if isinstance(raw, list):
                raw = ''.join(part.get('text', '') for part in raw if part.get('type') == 'text')
            if raw.strip().startswith('```'):
                raw = raw.strip().split('\n', 1)[1].rsplit('```', 1)[0].strip()
            try:
                jsonschema.validate(json.loads(raw), json_schema)
            except jsonschema.ValidationError as exc:
                raise ValueError('The response did not match the requested JSON schema: ' + exc.message) from exc
            reply.content = raw
    response_validator = validate_response
    if provider_blocked('claude'):
        if local_busy:
            raise CapacityBusy('Local AI is busy; retry shortly.', 5)
        raise AIServiceUnavailable('The AI service is unavailable. The administrator needs to check the Claude API credentials.')
    with model_slot('claude', None, estimate):
        try:
            from pure_multi_agent.capacity import model_slot as distributed_claude_slot
            with distributed_claude_slot():
                model = claude(claude_limit).bind_tools(tools, **({'tool_choice': 'any'} if require_tools else {})) if tools else claude(claude_limit)
                # LangChain tools validate arguments before execution. Return
                # errors to Claude through the graph so it can repair a call.
                current_messages = provider_messages(messages, 'Claude', claude(claude_limit).model)
                if message_preparer:
                    current_messages = message_preparer(current_messages)
                from pure_multi_agent.claude_policy import prepare_langchain
                current_messages = prepare_langchain(current_messages, tools)
                reply = measured_invoke(model, current_messages, 'claude', claude(claude_limit).model)
                try:
                    reply = _validate(reply, tools, require_tools=require_tools)
                    if response_validator:
                        response_validator(reply)
                    if tool_call_validator:
                        for call in reply.tool_calls:
                            tool_call_validator(call)
                except ValueError as validation_error:
                    if single_attempt:
                        raise InvalidToolResponse('Research response was invalid; no second paid request was made.') from validation_error
                    # Retry the model only: no invalid or duplicate tool is executed.
                    from langchain_core.messages import HumanMessage
                    correction = 'Your previous response did not match the available tools. Allowed tools: ' + ', '.join(t.name for t in tools)
                    correction += '. Use only these tools with their declared parameters.' if tools else '. Return a text answer without tool calls.'
                    correction += '\nValidation failure: ' + str(validation_error)[:4000]
                    try:
                        reply = _validate(measured_invoke(model, [*current_messages, HumanMessage(content=correction)], 'claude', claude(claude_limit).model), tools,
                            require_tools=require_tools)
                        if response_validator:
                            response_validator(reply)
                        if tool_call_validator:
                            for call in reply.tool_calls:
                                tool_call_validator(call)
                    except ValueError as invalid:
                        raise InvalidToolResponse('Tool arguments remained invalid after one correction attempt.') from invalid
                reply.response_metadata['routing_provider'] = 'claude'
                reply.response_metadata['routing_model'] = claude(claude_limit).model
                logger.info('AI response provider=claude tool_calls=%s', len(reply.tool_calls))
                return reply
        except Exception as exc:
            if getattr(exc, 'status_code', None) in (401, 403):
                block_provider('claude', 60)
                if local_busy:
                    raise CapacityBusy('Local AI is busy; retry shortly.', 5) from exc
                raise AIServiceUnavailable('The AI service is unavailable. The administrator needs to check the Claude API credentials.') from exc
            if getattr(exc, 'status_code', None) in (429, 529):
                raise CapacityBusy('Claude is busy', 15) from exc
            raise
