"""Generate URL-only environment files for all five checkouts from one matrix."""
import argparse
import json
import os
from pathlib import Path
from urllib.parse import urlparse

REPOS = {"backend": "Kormic_backend_sahil_ammar", "student": "Kormic_frontend_student_sahil_ammar",
    "university": "Kormic_frontend_University_sahil_ammar", "institute": "Kormic_frontend_Institutes_sahil_ammar",
    "superuser": "Kormic_frontend_Superuser_sahil_ammar"}


def resolve(environment, matrix):
    values = {key: os.path.expandvars(value) for key, value in matrix[environment].items()}
    for key, value in values.items():
        parsed = urlparse(value)
        if ("$" in value or not parsed.hostname or parsed.username or parsed.password or
            parsed.query or parsed.fragment or parsed.path not in ("", "/") or
            parsed.scheme not in (("http", "https") if environment == "local" else ("https",))):
            raise ValueError(f"Configure a valid {environment} {key} origin (HTTPS outside local).")
    return {key: value.rstrip("/") for key, value in values.items()}


def render(environment, values):
    api = values["api"]
    result = {role: {"VITE_API_BASE_URL": api, "VITE_APP_ENV": environment}
              for role in ("superuser", "university", "institute")}
    result["student"] = {"EXPO_PUBLIC_API_BASE_URL": api + "/api", "EXPO_PUBLIC_APP_ENV": environment}
    result["backend"] = {"KORMIC_ENVIRONMENT": environment,
        "DJANGO_ALLOWED_HOSTS": urlparse(api).hostname,
        "DJANGO_CORS_ALLOWED_ORIGINS": ",".join(values[r] for r in ("student", "superuser", "university", "institute")),
        "GITHUB_OAUTH_REDIRECT_URI": api + "/api/auth/github/callback/",
        "CLAIM_PAGE_URL": values["student"] + "/claim"}
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("environment", choices=("local", "staging", "production"))
    parser.add_argument("--root", type=Path, required=True, help="Directory holding the five checkouts")
    parser.add_argument("--matrix", type=Path, default=Path(__file__).resolve().parents[1] / "deploy/environments.json")
    args = parser.parse_args()
    values = resolve(args.environment, json.loads(args.matrix.read_text()))
    rendered = render(args.environment, values)
    # Validate all paths before creating anything. Never modify secret .env files.
    for repo in REPOS.values():
        if not (args.root / repo).is_dir():
            raise SystemExit(f"Missing checkout: {repo}")
    for role, repo in REPOS.items():
        path = args.root / repo / (".env.urls" if role == "backend" else ".env.local")
        if path.exists() and not path.read_text().startswith("# Generated by backend/scripts/configure_environment.py"):
            raise SystemExit(f"Refusing to overwrite manually maintained file: {path}")
    for role, variables in rendered.items():
        path = args.root / REPOS[role] / (".env.urls" if role == "backend" else ".env.local")
        path.write_text("# Generated by backend/scripts/configure_environment.py; contains URLs only.\n" +
                        "".join(f"{key}={value}\n" for key, value in variables.items()))
        print(path)


if __name__ == "__main__":
    main()
