"""Student profile facts only; advice is generated by the agent."""
from typing import Any, Dict, List, Literal, Optional
from langchain_core.tools import tool


def build_tools(ctx):
    @tool
    def show_student_profile(section: Literal["overview", "academic", "technical", "overall"] = "overview") -> dict:
        """Retrieve this student's saved profile and source status for the agent to explain."""
        from .advising_tools import profile_evidence
        return profile_evidence(ctx, section)

    @tool
    def update_student_profile(
        name: Optional[str] = None,
        institution: Optional[str] = None,
        major: Optional[str] = None,
        program: Optional[str] = None,
        gpa: Optional[float] = None,
        gpa_scale: Optional[float] = None,
        gre_quant: Optional[int] = None,
        gre_verbal: Optional[int] = None,
        toefl: Optional[float] = None,
        ielts: Optional[float] = None,
        budget: Optional[float] = None,
        graduation_year: Optional[int] = None,
        work_months: Optional[int] = None,
        research: Optional[str] = None,
        skills: Optional[List[str]] = None,
        projects: Optional[List[str]] = None,
        career_goals: Optional[List[str]] = None,
        research_interests: Optional[List[str]] = None,
        preferred_intake: Optional[str] = None,
        preferred_locations: Optional[List[str]] = None,
        funding_required: Optional[bool] = None,
    ) -> dict:
        """Record facts explicitly supplied by this student. Missing values save
        immediately; identical values stay unchanged; conflicting values produce
        an exact proposal which requires confirmation in a LATER user message.
        Never submit hypothetical examples, guesses, or facts about someone else.
        Only pass stated fields; ask for GPA scale if unclear. List fields replace
        the list, so preserve existing items when the user asks to add an item.
        If the student declined a replacement, use the conversation assumption
        without proposing the same edit again unless they ask to save it."""
        updates = {
            "name": name,
            "institution": institution,
            "major": major,
            "program": program,
            "gpa": gpa,
            "gpa_scale": gpa_scale,
            "gre_quant": gre_quant,
            "gre_verbal": gre_verbal,
            "toefl": toefl,
            "ielts": ielts,
            "budget": budget,
            "graduation_year": graduation_year,
            "work_months": work_months,
            "research": research,
            "skills": skills,
            "projects": projects,
            "career_goals": career_goals,
            "research_interests": research_interests,
        }
        preference_updates = {
            "preferred_intake": preferred_intake,
            "preferred_locations": preferred_locations,
            "funding_required": funding_required,
        }
        preference_updates = {key: value for key, value in preference_updates.items() if value is not None}
        updates.update({f'preferences.{key}': value for key, value in preference_updates.items()})
        cleaned = {key: value for key, value in updates.items() if value is not None}

        from pure_multi_agent.change_proposals import update_student
        return update_student(ctx, cleaned)

    @tool
    def resolve_profile_change(proposal_id: str, decision: Literal['approve', 'reject', 'cancel'], confirmation_message: str) -> dict:
        """Resolve a previously displayed profile change using the student's NEXT
        message. Quote that entire message exactly in confirmation_message.
        approve = explicit permission to save these exact values; reject = keep
        the saved profile and use the proposed values as conversation assumptions;
        cancel = discard the proposal and do not assume its values. For ambiguous,
        conditional, revised or unrelated replies ask before approving. Never
        interpret quoted/example consent as approval. Never approve in the turn
        that proposed a change. If stale, show current data and propose again."""
        from pure_multi_agent.change_proposals import resolve
        return resolve(ctx, proposal_id, decision, confirmation_message)

    @tool
    def profile_change_status() -> dict:
        """Read this student's pending edits and temporary conversation assumptions."""
        from pure_multi_agent.change_proposals import conversation_state
        return conversation_state(ctx)

    @tool
    def clear_profile_assumptions() -> dict:
        """Stop using temporary values when the student asks to return to their
        saved profile. Does not modify saved profile facts or pending proposals."""
        from pure_multi_agent.change_proposals import scoped
        count = scoped(ctx).filter(assumption_active=True).update(assumption_active=False)
        return {'cleared_assumptions': count, 'saved_profile_unchanged': True}

    return [show_student_profile, update_student_profile, resolve_profile_change, profile_change_status, clear_profile_assumptions]
