"""Student profile facts only; advice is generated by the agent."""
from typing import Any, Dict, List, Literal, Optional
from langchain_core.tools import tool


def build_tools(ctx):
    @tool
    def show_student_profile(section: Literal["overview", "academic", "technical", "overall"] = "overview") -> dict:
        """Retrieve this student's saved profile and source status for the agent to explain."""
        from .advising_tools import profile_evidence
        return profile_evidence(ctx, section)

    @tool
    def update_student_profile(
        name: Optional[str] = None,
        institution: Optional[str] = None,
        major: Optional[str] = None,
        program: Optional[str] = None,
        gpa: Optional[float] = None,
        gpa_scale: Optional[float] = None,
        gre_quant: Optional[int] = None,
        gre_verbal: Optional[int] = None,
        toefl: Optional[float] = None,
        ielts: Optional[float] = None,
        budget: Optional[float] = None,
        graduation_year: Optional[int] = None,
        work_months: Optional[int] = None,
        research: Optional[str] = None,
        skills: Optional[List[str]] = None,
        projects: Optional[List[str]] = None,
        career_goals: Optional[List[str]] = None,
        research_interests: Optional[List[str]] = None,
        preferred_intake: Optional[str] = None,
        preferred_locations: Optional[List[str]] = None,
        funding_required: Optional[bool] = None,
    ) -> str:
        """Save profile facts the student just stated or corrected in chat --
        GPA, test scores (GRE/TOEFL/IELTS), budget, institution, major,
        program, graduation year, work experience, skills, projects, or
        research interests, career goals, preferred intake/locations, or
        funding needs. Call this immediately whenever such a fact
        appears in the student's message, even if they were really asking
        about something else -- this is the only way that fact gets saved;
        if you don't call it, it's lost after this turn. Only pass the
        fields actually stated; leave everything else unset."""
        updates = {
            "name": name,
            "institution": institution,
            "major": major,
            "program": program,
            "gpa": gpa,
            "gpa_scale": gpa_scale,
            "gre_quant": gre_quant,
            "gre_verbal": gre_verbal,
            "toefl": toefl,
            "ielts": ielts,
            "budget": budget,
            "graduation_year": graduation_year,
            "work_months": work_months,
            "research": research,
            "skills": skills,
            "projects": projects,
            "career_goals": career_goals,
            "research_interests": research_interests,
        }
        preference_updates = {
            "preferred_intake": preferred_intake,
            "preferred_locations": preferred_locations,
            "funding_required": funding_required,
        }
        preference_updates = {key: value for key, value in preference_updates.items() if value is not None}
        if preference_updates:
            updates["preferences"] = {**(ctx["student_profile"].get("preferences") or {}), **preference_updates}
        cleaned = {key: value for key, value in updates.items() if value is not None}

        if not cleaned:
            return "No profile fields were provided to update."

        ctx["student_profile"].update(cleaned)
        return f"Profile updated: {', '.join(cleaned.keys())}."

    return [show_student_profile, update_student_profile]
