# Generated by Django 5.2.17 on 2026-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_country_default'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='university',
            name='university_country_us',
        ),
        migrations.AddField(
            model_name='university',
            name='record_origin',
            field=models.CharField(choices=[('registered', 'Registered'), ('researched', 'Researched')], default='registered', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.CheckConstraint(condition=models.Q(('country', 'US'), ('record_origin', 'researched'), _connector='OR'), name='university_country_us'),
        ),
    ]
