# Generated by Django 5.2.17 on 2026-09-26 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_api', '0010_university_policy_details'),
        ('universities', '0005_university_country_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.studentprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('student_to_university', 'Student agent to university agent'), ('university_to_student', 'University agent to student agent')], max_length=30)),
                ('question', models.TextField()),
                ('question_hash', models.CharField(max_length=64)),
                ('raised_by_agent', models.CharField(max_length=255)),
                ('recipient_agent', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('unanswered', 'Unanswered'), ('answered', 'Answered')], db_index=True, default='unanswered', max_length=15)),
                ('answer', models.TextField(blank=True)),
                ('answer_scope', models.CharField(default='private', max_length=20)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='agent_queries.agentconversation')),
                ('knowledge_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_api.universityknowledgeentry')),
            ],
        ),
        migrations.CreateModel(
            name='AgentConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=30)),
                ('actor_name', models.CharField(max_length=255)),
                ('kind', models.CharField(default='message', max_length=30)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_queries.agentconversation')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_queries.agentquery')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentconversation',
            constraint=models.UniqueConstraint(fields=('student', 'university'), name='unique_agent_conversation_pair'),
        ),
        migrations.AddIndex(
            model_name='agentquery',
            index=models.Index(fields=['conversation', 'direction', 'status', '-created_at'], name='agent_query_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentquery',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'unanswered')), fields=('conversation', 'direction', 'question_hash'), name='unique_open_agent_query'),
        ),
        migrations.AddIndex(
            model_name='agentconversationmessage',
            index=models.Index(fields=['conversation', 'created_at', 'id'], name='agent_message_thread_idx'),
        ),
    ]
