# Generated by Django 5.2.17 on 2026-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_key', models.CharField(max_length=100, unique=True)),
                ('run_id', models.UUIDField()),
                ('status', models.CharField(default='working', max_length=20)),
                ('label', models.CharField(default='Thinking…', max_length=180)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
