# Generated by Django 5.2.17 on 2026-09-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_queries', '0002_agentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRateWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCapacitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180)),
                ('number', models.PositiveIntegerField()),
                ('token', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'number'), name='unique_agent_capacity_slot')],
            },
        ),
    ]
