# Generated by Django 5.2.17 on 2026-10-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_queries', '0003_agentratewindow_agentcapacityslot'),
        ('universities', '0006_remove_university_university_country_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentquery',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.knowledgegroup'),
        ),
    ]
