# Generated by Django 5.2.17 on 2026-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
